import { useState, useCallback, useEffect } from 'react';
import { useWallet } from '../contexts/WalletContext';
import { createPatchedPublicDataProvider } from '../lib/midnight';
import { CompiledContract } from '@midnight-ntwrk/compact-js';
import { createUnprovenCallTx, submitTxAsync } from '@midnight-ntwrk/midnight-js-contracts';

// Import from managed/ directory (generated by compact compiler)
// After running yarn compile and yarn copy:managed, these types will be available
let Contract: any = null;
let ledger: any = null;

try {
  const mod = await import('../managed/contract/index.js');
  Contract = mod.Contract;
  ledger = mod.ledger;
} catch {
  // Contract not compiled yet — show placeholder UI
}

type ProofStatus = 'idle' | 'generating' | 'submitting' | 'success' | 'error';

type ContractState = {
  min_cgpa: bigint;
  min_projects: bigint;
  requires_python: boolean;
  is_active: boolean;
  deadline: bigint;
  total_verified: bigint;
  max_claims: bigint;
} | null;

function getCompiledContract() {
  if (!Contract) throw new Error('Contract not compiled. Run yarn compile and yarn copy:managed first.');
  return CompiledContract.make('ProofPass', Contract).pipe(
    CompiledContract.withVacantWitnesses,
    CompiledContract.withCompiledFileAssets(new URL('/managed', window.location.origin).toString()),
  ) as any;
}

export default function StudentPage() {
  const { session, isConnected, connect, walletStatus, isConnecting } = useWallet();

  // Student's private credentials (these NEVER leave the browser)
  const [cgpa, setCgpa] = useState('8.5');
  const [projects, setProjects] = useState('4');
  const [hasPython, setHasPython] = useState(true);
  const [studentIdHex, setStudentIdHex] = useState('');

  // Contract state
  const [contractAddress, setContractAddress] = useState('');
  const [onChainState, setOnChainState] = useState<ContractState>(null);
  const [loadingState, setLoadingState] = useState(false);

  // Proof state
  const [proofStatus, setProofStatus] = useState<ProofStatus>('idle');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [txId, setTxId] = useState<string | null>(null);

  // Load saved contract address
  useEffect(() => {
    const saved = localStorage.getItem('DEPLOYED_CONTRACT_ADDRESS') ?? '';
    setContractAddress(saved);
    // Generate a random student ID if not set
    const savedId = localStorage.getItem('STUDENT_ID');
    if (savedId) {
      setStudentIdHex(savedId);
    } else {
      const arr = new Uint8Array(32);
      crypto.getRandomValues(arr);
      const hex = Array.from(arr, b => b.toString(16).padStart(2, '0')).join('');
      setStudentIdHex(hex);
      localStorage.setItem('STUDENT_ID', hex);
    }
  }, []);

  // Fetch on-chain state when contract address is known and session is connected
  const fetchContractState = useCallback(async () => {
    if (!session || !contractAddress || !ledger) return;
    setLoadingState(true);
    try {
      const provider = createPatchedPublicDataProvider(
        session.config.indexerUri,
        session.config.indexerWsUri,
      );
      const raw = await provider.queryContractState(contractAddress);
      if (raw) setOnChainState(ledger(raw.data));
    } catch (e) {
      console.error('Failed to fetch state:', e);
    } finally {
      setLoadingState(false);
    }
  }, [session, contractAddress]);

  useEffect(() => {
    if (isConnected) fetchContractState();
  }, [isConnected, fetchContractState]);

  const handleProve = useCallback(async () => {
    if (!session || !contractAddress) return;
    setProofStatus('generating');
    setErrorMsg(null);
    setTxId(null);

    try {
      const cgpaInt = BigInt(Math.round(parseFloat(cgpa) * 10));
      const projectsInt = BigInt(parseInt(projects, 10));

      // Convert hex student ID to Uint8Array
      const studentIdBytes = new Uint8Array(32);
      const hex = studentIdHex.replace(/^0x/, '');
      for (let i = 0; i < Math.min(hex.length / 2, 32); i++) {
        studentIdBytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
      }

      const callTxData = await createUnprovenCallTx(session.providers as any, {
        compiledContract: getCompiledContract(),
        contractAddress,
        circuitId: 'verify_eligibility',
        witnesses: {
          // PRIVATE: these values are NEVER sent to the blockchain
          student_credentials: () => ({
            cgpa: cgpaInt,
            project_count: projectsInt,
            has_python: hasPython,
            student_id: studentIdBytes,
          }),
        },
        args: [],
      });

      setProofStatus('submitting');

      const result = await submitTxAsync(session.providers as any, {
        unprovenTx: callTxData.private.unprovenTx,
      });

      setTxId(typeof result === 'string' ? result : 'submitted');
      setProofStatus('success');

      // Refresh on-chain state
      setTimeout(fetchContractState, 3000);
    } catch (e: any) {
      setProofStatus('error');
      setErrorMsg(e?.message ?? String(e));
    }
  }, [session, contractAddress, cgpa, projects, hasPython, studentIdHex, fetchContractState]);

  // Compute local checks (client-side preview — real check happens in ZK circuit)
  const cgpaNum = parseFloat(cgpa) || 0;
  const projectsNum = parseInt(projects, 10) || 0;
  const meetsGpa = onChainState ? cgpaNum * 10 >= Number(onChainState.min_cgpa) : cgpaNum >= 8;
  const meetsProjects = onChainState ? projectsNum >= Number(onChainState.min_projects) : projectsNum >= 2;
  const meetsPython = onChainState ? !onChainState.requires_python || hasPython : hasPython;

  // ── Not connected state ──────────────────────────────────────────────────
  if (!isConnected) {
    return (
      <div className="page-wrapper">
        <div className="page-content">
          <div className="wallet-prompt animate-fade-up">
            <span className="wallet-prompt-icon">🎓</span>
            <h2>Student Portal</h2>
            <p>Connect your 1AM wallet to privately prove your eligibility for internships and jobs using Zero-Knowledge proofs.</p>
            {walletStatus === 'not-found' ? (
              <a href="https://chromewebstore.google.com/search/1am" target="_blank" rel="noopener noreferrer" className="btn btn-primary btn-lg">
                📦 Install 1AM Wallet
              </a>
            ) : (
              <button className="btn btn-primary btn-lg" onClick={() => connect('preprod')} disabled={isConnecting}>
                {isConnecting ? <><span className="spinner" /> Connecting...</> : '🔗 Connect Wallet'}
              </button>
            )}
            <div style={{ marginTop: 40 }}>
              <div className="card" style={{ maxWidth: 480, margin: '0 auto', textAlign: 'left' }}>
                <p className="heading-md" style={{ marginBottom: 12 }}>🔒 Privacy guarantee</p>
                <p className="text-secondary" style={{ fontSize: '0.9rem' }}>
                  Your actual CGPA, project count, and credentials{' '}
                  <strong style={{ color: 'var(--text-primary)' }}>never leave your browser</strong>.
                  Only a ZK proof is submitted to Midnight — proving you meet the threshold without
                  revealing your exact values.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page-wrapper">
      <div className="page-content animate-fade-up">
        {/* Header */}
        <div className="section-header" style={{ marginBottom: 40 }}>
          <div className="section-header-left">
            <h1 className="heading-xl">Student Portal</h1>
            <p className="text-secondary">
              Enter your private credentials below. They stay on your device — only the ZK proof is sent.
            </p>
          </div>
          <span className="badge badge-success">🔐 Privacy Protected</span>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 360px', gap: 32, alignItems: 'start' }}>
          {/* Left: credential form */}
          <div>
            {/* Contract address input */}
            <div className="glass-panel" style={{ marginBottom: 24 }}>
              <p className="heading-md" style={{ marginBottom: 16 }}>📍 Contract Address</p>
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Opportunity Contract Address</label>
                <input
                  id="contract-address-input"
                  className="form-input form-input-mono"
                  value={contractAddress}
                  onChange={e => setContractAddress(e.target.value)}
                  placeholder="Paste the recruiter's contract address..."
                />
              </div>
              {contractAddress && (
                <button
                  className="btn btn-secondary btn-sm"
                  style={{ marginTop: 12 }}
                  onClick={fetchContractState}
                  disabled={loadingState}
                >
                  {loadingState ? <><span className="spinner" style={{ width: 14, height: 14, borderWidth: 2 }} /> Loading...</> : '🔄 Fetch Requirements'}
                </button>
              )}
            </div>

            {/* Private credentials */}
            <div className="glass-panel" style={{ marginBottom: 24 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
                <p className="heading-md">🔐 Your Private Credentials</p>
                <span className="badge badge-violet">PRIVATE · Never on-chain</span>
              </div>

              <div className="credential-grid">
                <div className="credential-card">
                  <span className="credential-private-badge">Private</span>
                  <div className="credential-label">CGPA</div>
                  <input
                    id="cgpa-input"
                    className="form-input"
                    style={{ fontSize: '1.4rem', fontWeight: 700, marginTop: 4 }}
                    type="number"
                    min="0"
                    max="10"
                    step="0.01"
                    value={cgpa}
                    onChange={e => setCgpa(e.target.value)}
                  />
                  <div className="credential-hint">Stored as integer × 10 in circuit</div>
                </div>

                <div className="credential-card">
                  <span className="credential-private-badge">Private</span>
                  <div className="credential-label">Projects</div>
                  <input
                    id="projects-input"
                    className="form-input"
                    style={{ fontSize: '1.4rem', fontWeight: 700, marginTop: 4 }}
                    type="number"
                    min="0"
                    max="100"
                    value={projects}
                    onChange={e => setProjects(e.target.value)}
                  />
                  <div className="credential-hint">Completed projects count</div>
                </div>
              </div>

              <div className="toggle-row">
                <div>
                  <div className="toggle-label">Python Proficiency</div>
                  <div className="toggle-desc">Check if you have Python skills</div>
                </div>
                <label className="toggle">
                  <input id="python-toggle" type="checkbox" checked={hasPython} onChange={e => setHasPython(e.target.checked)} />
                  <span className="toggle-slider" />
                </label>
              </div>

              <div className="form-group" style={{ marginBottom: 0, marginTop: 16 }}>
                <label className="form-label">Your Anonymous Student ID (auto-generated)</label>
                <input
                  className="form-input form-input-mono"
                  value={studentIdHex}
                  onChange={e => setStudentIdHex(e.target.value)}
                  style={{ fontSize: '0.75rem' }}
                />
                <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4 }}>
                  This is hashed into a nullifier on-chain. Store it to prove eligibility or detect double-claim.
                </p>
              </div>
            </div>

            {/* Prove button */}
            {proofStatus === 'idle' || proofStatus === 'error' ? (
              <button
                id="prove-eligibility-btn"
                className="btn btn-primary btn-lg"
                style={{ width: '100%' }}
                onClick={handleProve}
                disabled={!contractAddress || proofStatus === 'error' && !errorMsg}
              >
                🔐 Generate Zero-Knowledge Proof
              </button>
            ) : proofStatus === 'generating' ? (
              <div className="status-bar status-bar-info">
                <span className="spinner" />
                <div>
                  <div style={{ fontWeight: 600 }}>Generating ZK Proof...</div>
                  <div style={{ fontSize: '0.8rem' }}>This may take 30–120 seconds. Do not close this tab.</div>
                </div>
              </div>
            ) : proofStatus === 'submitting' ? (
              <div className="status-bar status-bar-warning">
                <span className="spinner" />
                <div>
                  <div style={{ fontWeight: 600 }}>Submitting to Midnight...</div>
                  <div style={{ fontSize: '0.8rem' }}>Check your 1AM wallet for a confirmation popup.</div>
                </div>
              </div>
            ) : null}

            {/* Result */}
            {proofStatus === 'success' && (
              <div className="proof-result proof-result-success animate-fade-in" style={{ marginTop: 24 }}>
                <div className="proof-icon">✅</div>
                <p className="heading-lg" style={{ color: 'var(--accent-emerald)', marginBottom: 8 }}>
                  Eligibility Proven!
                </p>
                <p className="text-secondary" style={{ marginBottom: 16 }}>
                  Your Zero-Knowledge proof was accepted. The recruiter can now see you're eligible — without knowing your exact CGPA, project count, or identity.
                </p>
                {txId && (
                  <div className="address-display" style={{ justifyContent: 'center' }}>
                    Tx: {txId.length > 20 ? `${txId.slice(0, 20)}...` : txId}
                  </div>
                )}
              </div>
            )}

            {proofStatus === 'error' && errorMsg && (
              <div className="proof-result proof-result-error animate-fade-in" style={{ marginTop: 24 }}>
                <div className="proof-icon">❌</div>
                <p className="heading-md" style={{ color: 'var(--accent-rose)', marginBottom: 8 }}>
                  Proof Rejected
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 16 }}>
                  {errorMsg.includes('Score below') || errorMsg.includes('CGPA')
                    ? 'Your CGPA does not meet the required threshold.'
                    : errorMsg.includes('Already verified')
                    ? 'You have already proved eligibility for this opportunity (nullifier exists).'
                    : errorMsg.includes('Insufficient project')
                    ? 'Your project count does not meet the minimum requirement.'
                    : errorMsg.includes('Python')
                    ? 'Python proficiency is required for this opportunity.'
                    : 'The ZK proof was rejected by the contract.'}
                </p>
                <details style={{ textAlign: 'left', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                  <summary>Technical details</summary>
                  <pre style={{ marginTop: 8, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>{errorMsg}</pre>
                </details>
                <button className="btn btn-secondary" style={{ marginTop: 16 }} onClick={() => { setProofStatus('idle'); setErrorMsg(null); }}>
                  Try Again
                </button>
              </div>
            )}
          </div>

          {/* Right: requirements panel */}
          <div style={{ position: 'sticky', top: 104 }}>
            <div className="glass-panel">
              <p className="heading-md" style={{ marginBottom: 4 }}>📋 Requirements Check</p>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 20 }}>
                Preview — actual proof runs in the ZK circuit
              </p>

              {onChainState ? (
                <>
                  <ul className="requirements-list" style={{ marginBottom: 20 }}>
                    <li className={`requirement-item ${meetsGpa ? 'met' : 'unmet'}`}>
                      <span className="requirement-name">CGPA ≥ {(Number(onChainState.min_cgpa) / 10).toFixed(1)}</span>
                      <span className="req-check">{meetsGpa ? '✅' : '❌'}</span>
                    </li>
                    <li className={`requirement-item ${meetsProjects ? 'met' : 'unmet'}`}>
                      <span className="requirement-name">Projects ≥ {Number(onChainState.min_projects)}</span>
                      <span className="req-check">{meetsProjects ? '✅' : '❌'}</span>
                    </li>
                    {onChainState.requires_python && (
                      <li className={`requirement-item ${meetsPython ? 'met' : 'unmet'}`}>
                        <span className="requirement-name">Python Required</span>
                        <span className="req-check">{meetsPython ? '✅' : '❌'}</span>
                      </li>
                    )}
                    <li className="requirement-item">
                      <span className="requirement-name">Contract Active</span>
                      <span className="req-check">{onChainState.is_active ? '✅' : '⏸️'}</span>
                    </li>
                    <li className="requirement-item">
                      <span className="requirement-name">Deadline</span>
                      <span className="req-check">
                        {Date.now() / 1000 < Number(onChainState.deadline) ? '✅' : '⏰'}
                      </span>
                    </li>
                  </ul>

                  <div className="divider" />

                  <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textAlign: 'center' }}>
                    Verified so far:{' '}
                    <strong style={{ color: 'var(--text-primary)' }}>{Number(onChainState.total_verified)}</strong>
                    {' '}/{' '}
                    <strong>{Number(onChainState.max_claims)}</strong> slots
                  </p>
                </>
              ) : (
                <div style={{ textAlign: 'center', padding: '24px 0', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                  {contractAddress
                    ? 'Enter contract address and click "Fetch Requirements"'
                    : 'Paste the recruiter\'s contract address to see requirements'}
                </div>
              )}
            </div>

            <div className="glass-panel" style={{ marginTop: 16 }}>
              <p className="heading-md" style={{ marginBottom: 12, fontSize: '0.95rem' }}>🔒 Privacy Model</p>
              <div style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
                <p>The recruiter <strong style={{ color: 'var(--accent-emerald)' }}>can</strong> see:</p>
                <ul style={{ marginLeft: 16, marginBottom: 12, marginTop: 4 }}>
                  <li>That requirements were met</li>
                  <li>Total number of verifications</li>
                  <li>An anonymous nullifier</li>
                </ul>
                <p>The recruiter <strong style={{ color: 'var(--accent-rose)' }}>cannot</strong> see:</p>
                <ul style={{ marginLeft: 16, marginTop: 4 }}>
                  <li>Your actual CGPA</li>
                  <li>Number of projects</li>
                  <li>Your identity or wallet</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
